### ISSUE TITLE
Add image storage

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/liquid-decidim-demo#28]

**Comment by jinjagit** [comment]
This article seems like it might have some interesting points / ideas related to image files and k8s: https://medium.com/flant-com/stateful-app-files-in-kubernetes-d015311e5e6b

**Comment by oliverbarnes** [comment]
Thanks, but better to go stateless as the author states at the end - less complicated, while preparing us for Real Life™️ apps that will definitely need their own storage

**Comment by oliverbarnes** [comment]
Now working with Linode's Object Storage (their S3)

**Comment by oliverbarnes** [comment]
Wasn't really working - images were being uploaded to the pod (and deleted on pod cyclings), and not to Linode's object storage.

After some time on this, I'm able to manually create objects from the rails console on production, but carrierwave somehow still doesn't play ball:

https://www.linode.com/community/questions/21593/carrierwave-and-linode-object-storage

**Comment by oliverbarnes** [comment]
Just started working after Simon logged in as admin from his machine 🤷 I then could upload on my end as well. Go figure
